build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    
        tests:
            dependencies:
                override:
                    - composer install --no-interaction --prefer-dist --ignore-platform-reqs
            tests:
                override:
                    - command: vendor/bin/phpunit --coverage-clover=coverage.clover
                      coverage:
                          file: coverage.clover
                          format: clover

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'migrations/*'
        - 'var/*'
        - 'public/*'
        - 'node_modules/*'
        - 'tools/*'
        - 'src/Guess/*'

checks:
    php:
        code_rating: true
        duplication: true