filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'migrations/*'
        - 'var/*'
        - 'public/*'
        - 'node_modules/*'
        - 'tools/*'
        - 'src/Guess/*'

checks:
    php:
        code_rating: true
        duplication: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true